name: icon-browser-adw
version: '0.1'
summary: Icon Browser for Adwaita
description: icon-browser-adw allows you to view the gnome desktop icons with adwaita, allowing you to copy the icon names for use in your projects.
base: core24
confinement: strict
grade: stable
license: GPL-3.0-or-later
compression: lzo

platforms:
  amd64:
  arm64:
  armhf:

apps:
  icon-browser-adw:
    command: bin/iconvwadw
    desktop: ${SNAPCRAFT_STAGE}/share/applications/io.github.rsvzz.iconvwadw.desktop
    extensions: [gnome]
    common-id: io.github.rsvzz.iconvwadw
    slots: [icon-browser-adw-dbus]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  icon-browser-adw:
    plugin: meson
    source: https://github.com/rsvzz/icon-browser-adw.git
    source-type: git
    source-tag: 0.1
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    build-packages:
      - meson
    stage-packages:
      - adwaita-icon-theme
    override-build: |
      snapcraftctl build
      rm -r ${SNAPCRAFT_PART_INSTALL}/share/applications/io.github.rsvzz.iconvwadw.desktop

  icon-browser-adw-files:
    source: .
    plugin: dump
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/share/applications -p
      cp ${SNAPCRAFT_PART_BUILD}/data/io.github.rsvzz.iconvwadw.desktop ${SNAPCRAFT_PART_INSTALL}/share/applications 

slots:
  icon-browser-adw-dbus:
    interface: dbus
    bus: session
    name: io.github.rsvzz.iconvwadw